---
title: "Custom annotations"
description: >
  Functions and objects for annotating the data panel.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Custom annotations}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r, echo = FALSE}
ragg_png = function(..., res = 150) {
  ragg::agg_png(..., res = res, units = "in")
}
knitr::opts_chunk$set(dev = "ragg_png")
```


## Required packages

```{r setup, message=FALSE}
library(penngradlings)
library(ggplot2)
library(grid)
library(gridtext)
```

### HTML textbox annotations with `annotation_textbox` 

```{r}
p <- ggplot(mtcars, aes(mpg, hp)) +
  geom_point()

p
```

```{r}
annotation <- "
  <span style=\"font-size:18px; font-family:'Piazzolla-Black';\">
   This is a cat:</span>
  <br><br>
  <span style=\"font-size:72px; color:'#7950F2';
   font-family:'FontAwesome5-Solid';\">cat</span>
  <br><br>
  Just look at this
  <span style=\"font-family:'PiazzollaSC-Regular';\">cat!</span>
"

tbox1 <- annotation_textbox(
  html = annotation,
  position = "top-right",
  halign = 0.5,
)

p + annotation_custom(tbox1)
```

```{r}
tbox2 <- annotation_textbox(
  html = annotation,
  position = "center",
  halign = 0.5,
  valign = 0.5,
  x_offset = -0.1,
  y_offset = 0.1,
  width = 0.4,
  height = 0.5
)

p + annotation_custom(tbox2)
```

